/*
 * Vidly Project Original (2026)
 * fikriaja1028 (GitHub.com/fikriaja1028)
 * Licenced Under GPL-3.0+
*/
package com.fikriaja.vidly.ui.screens.player

import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.Player
import androidx.media3.common.TrackSelectionOverride
import androidx.media3.common.util.UnstableApi
import com.fikriaja.vidly.domain.model.StreamBundle
import com.fikriaja.vidly.domain.model.SubtitleItem
import java.util.Locale
import javax.inject.Inject

@UnstableApi
class PlayerTrackManager @Inject constructor() {

    fun updateCcState(player: Player, enabled: Boolean, preferredLang: String?) {
        val parametersBuilder = player.trackSelectionParameters.buildUpon()
        
        if (enabled) {
            parametersBuilder.setTrackTypeDisabled(C.TRACK_TYPE_TEXT, false)
            
            if (preferredLang != null) {
                parametersBuilder.setPreferredTextLanguage(preferredLang)
                parametersBuilder.clearOverridesOfType(C.TRACK_TYPE_TEXT)
            }
            
            val currentTracks = player.currentTracks
            val hasActiveTextTrack = currentTracks.groups.any { it.type == C.TRACK_TYPE_TEXT && it.isSelected }
            
            if (!hasActiveTextTrack) {
                for (group in currentTracks.groups) {
                    if (group.type == C.TRACK_TYPE_TEXT && group.isSupported) {
                        parametersBuilder.addOverride(
                            TrackSelectionOverride(group.mediaTrackGroup, 0)
                        )
                        break
                    }
                }
            }
        } else {
            parametersBuilder.setTrackTypeDisabled(C.TRACK_TYPE_TEXT, true)
            parametersBuilder.clearOverridesOfType(C.TRACK_TYPE_TEXT)
        }
        
        player.trackSelectionParameters = parametersBuilder.build()
    }

    fun createSubtitleConfigs(bundle: StreamBundle): List<MediaItem.SubtitleConfiguration> {
        return bundle.subtitles.filter { it.url.isNotBlank() }.map { subtitle ->
            // FIX(subtitle mojibake): URL may still carry fmt=json3/srv3 after cache;
            // force vtt so ExoPlayer's WebvttDecoder receives valid WebVTT UTF-8 bytes
            // instead of JSON/XML which renders as garbled text (• -> •).
            val normalizedUrl = subtitle.url
                .replace("fmt=json3", "fmt=vtt")
                .replace("fmt=srv3", "fmt=vtt")
                .replace("fmt=ttml", "fmt=vtt")
                .let { u -> if (!u.contains("fmt=")) u + (if (u.contains("?")) "&" else "?") + "fmt=vtt" else u }

            // Force VTT mimeType – after normalisation all subtitles are WebVTT.
            // Letting json3 fall through to TEXT_VTT while still fetching json3
            // caused the decoder to interpret JSON bytes as VTT cues (mojibake).
            val mimeType = MimeTypes.TEXT_VTT

            val label = if (subtitle.isAutoGenerated) {
                "${Locale.forLanguageTag(subtitle.languageTag).displayLanguage} (Auto-generated)"
            } else {
                Locale.forLanguageTag(subtitle.languageTag).displayLanguage
            }

            MediaItem.SubtitleConfiguration.Builder(android.net.Uri.parse(normalizedUrl))
                .setMimeType(mimeType)
                .setLanguage(subtitle.languageTag)
                .setLabel(label)
                .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
                .build()
        }
    }
}
