/*
 * Vidly Project Original (2026)
 * fikriaja1028 (GitHub.com/fikriaja1028)
 * Licenced Under GPL-3.0+
*/
package com.fikriaja.vidly.domain.model

import androidx.compose.runtime.Immutable
import androidx.annotation.Keep

@Keep
@Immutable
data class StreamItem(
    val url: String,
    val quality: String,
    val format: String,
    val size: Long = -1,
    val isAdaptive: Boolean = false,
    val languageTag: String? = null,
    val trackType: String? = null
)

@Keep
@Immutable
data class SubtitleItem(
    val url: String,
    val languageTag: String,
    val format: String, // e.g., "vtt", "ttml"
    val isAutoGenerated: Boolean = false
)
